-- AtlasLoot loot tables localization file
-- NOTE: THIS FILE IS AUTO-GENERATED BY A TOOL, ANY MANUALLY CHANGE MIGHT BE OVERWRITTEN.
-- $Id: localization.lua 2725 2010-07-18 16:25:23Z arith $

local process = function(category,check,data) if not AtlasLoot_Data[category] or #AtlasLoot_Data[category] ~= check then return end for i = 1, #data do if data[i] and data[i] ~= ""  then AtlasLoot_Data[category][i][4] = data[i] end end data = nil end
local locale = GetLocale()
if locale == "frFR" then
end